/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import javax.swing.JOptionPane;
import persistencia.BD;
import controle.controladorCadastroAmigo;
import controle.controladorCadastroAvaliacao;
import controle.controladorCadastroFilme;
/**
 *
 * @author felip
 */
public class JanelaAmigosCinema extends javax.swing.JFrame {
    
    /**
     * Creates new form JanelaAmigosCinema
     */
    public JanelaAmigosCinema() {
        BD.criaConexaoComando();
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amigos_cinemaMenuBar = new javax.swing.JMenuBar();
        cadastrar_amigoItemMenu = new javax.swing.JMenu();
        cadastrarAmigo = new javax.swing.JMenuItem();
        filmeMenu = new javax.swing.JMenu();
        cadastrarFilme = new javax.swing.JMenuItem();
        avaliacaoMenu = new javax.swing.JMenu();
        cadastrar_avaliacaoItemMenu = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                terminarSistema(evt);
            }
        });

        cadastrar_amigoItemMenu.setText("Amigo");

        cadastrarAmigo.setText("Cadastrar");
        cadastrarAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarAmigoActionPerformed(evt);
            }
        });
        cadastrar_amigoItemMenu.add(cadastrarAmigo);

        amigos_cinemaMenuBar.add(cadastrar_amigoItemMenu);

        filmeMenu.setText("Filme");
        filmeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmeMenuActionPerformed(evt);
            }
        });

        cadastrarFilme.setText("Cadastrar");
        cadastrarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFilmeActionPerformed(evt);
            }
        });
        filmeMenu.add(cadastrarFilme);

        amigos_cinemaMenuBar.add(filmeMenu);

        avaliacaoMenu.setText("Avaliação");

        cadastrar_avaliacaoItemMenu.setText("Cadastrar");
        cadastrar_avaliacaoItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_avaliacaoItemMenuActionPerformed(evt);
            }
        });
        avaliacaoMenu.add(cadastrar_avaliacaoItemMenu);

        jMenuItem1.setText("Pesquisar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
                pesquisarAvaliacoes(evt);
            }
        });
        avaliacaoMenu.add(jMenuItem1);

        amigos_cinemaMenuBar.add(avaliacaoMenu);

        setJMenuBar(amigos_cinemaMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar_avaliacaoItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_avaliacaoItemMenuActionPerformed
        new controladorCadastroAvaliacao();
        
    }//GEN-LAST:event_cadastrar_avaliacaoItemMenuActionPerformed

    private void terminarSistema(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_terminarSistema
        BD.fechaComandoConexao();
        System.exit(0); 
    }//GEN-LAST:event_terminarSistema

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void pesquisarAvaliacoes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarAvaliacoes
       new JanelaPesquisaAvaliacoes().setVisible(true);
    }//GEN-LAST:event_pesquisarAvaliacoes

    private void cadastrarAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAmigoActionPerformed
        new controladorCadastroAmigo();
        //new JanelaAmigosCinema().setVisible(true);
    }//GEN-LAST:event_cadastrarAmigoActionPerformed

    private void filmeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmeMenuActionPerformed
         informarServicosIndisponiveis();
    }//GEN-LAST:event_filmeMenuActionPerformed

    private void cadastrarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFilmeActionPerformed
        new controladorCadastroFilme();
    }//GEN-LAST:event_cadastrarFilmeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaAmigosCinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaAmigosCinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaAmigosCinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaAmigosCinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaAmigosCinema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar amigos_cinemaMenuBar;
    private javax.swing.JMenu avaliacaoMenu;
    private javax.swing.JMenuItem cadastrarAmigo;
    private javax.swing.JMenuItem cadastrarFilme;
    private javax.swing.JMenu cadastrar_amigoItemMenu;
    private javax.swing.JMenuItem cadastrar_avaliacaoItemMenu;
    private javax.swing.JMenu filmeMenu;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables

    private void informarServicosIndisponiveis() {
        JOptionPane.showMessageDialog(this, "Serviço indisponivel", "Informação", JOptionPane.INFORMATION_MESSAGE);
    }
}
