/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author felip
 */
public class PainelFiltrosFilmeCompanhiaCinematografica extends javax.swing.JPanel {

    /**
     * Creates new form PainelFiltrosFilmeCompanhiaCinematografica
     */
    public PainelFiltrosFilmeCompanhiaCinematografica() {
        initComponents();
        limparFiltros();
    }
    
    public char getOscarMelhorFilme(){
        char oscar_melhor_filme = 'X';
        if(oscar_melhor_filmeButtonGroup.getSelection() != null){
            switch(oscar_melhor_filmeButtonGroup.getSelection().getMnemonic()){
                case 0 : oscar_melhor_filme = 'T'; break;
                case 1 : oscar_melhor_filme = 'F';
            }
        }
        return oscar_melhor_filme;
    }
    
    public void limparFiltros(){
        oscar_melhor_filmeButtonGroup.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        oscar_melhor_filmeButtonGroup = new javax.swing.ButtonGroup();
        oscar_melhor_filmeLabel = new javax.swing.JLabel();
        simRadioButton = new javax.swing.JRadioButton();
        naoRadioButton = new javax.swing.JRadioButton();

        setLayout(new java.awt.GridBagLayout());

        oscar_melhor_filmeLabel.setText("Oscar de Melhor Filme");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 0, 0);
        add(oscar_melhor_filmeLabel, gridBagConstraints);

        oscar_melhor_filmeButtonGroup.add(simRadioButton);
        simRadioButton.setText("sim");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 24, 0, 0);
        add(simRadioButton, gridBagConstraints);

        oscar_melhor_filmeButtonGroup.add(naoRadioButton);
        naoRadioButton.setMnemonic('\u0001');
        naoRadioButton.setText("não");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 26, 0, 0);
        add(naoRadioButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton naoRadioButton;
    private javax.swing.ButtonGroup oscar_melhor_filmeButtonGroup;
    private javax.swing.JLabel oscar_melhor_filmeLabel;
    private javax.swing.JRadioButton simRadioButton;
    // End of variables declaration//GEN-END:variables
}
