/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author felip
 */
public class PainelFilmesCompanhiaCinematografica extends javax.swing.JPanel {

    /**
     * Creates new form PainelFilmesCompanhiaCinematografica
     */
    public PainelFilmesCompanhiaCinematografica() {
        initComponents();
    }
    
    public boolean isOscarMelhorFilme() {
        return oscar_filmeCheckBox.isSelected();
    }

    public void setOscarMelhorFilme(boolean oscar_melhor_filme) {
        oscar_filmeCheckBox.setSelected(oscar_melhor_filme);
    }

    public String getOscarMelhorDiretor() {
        String diretor = oscar_diretorTextField.getText();
        if (diretor.isEmpty()) {
            return null;
        } else {
            return diretor;
        }
    }

    public void setOscarMelhorDiretor(String diretor) {
        oscar_diretorTextField.setText(diretor);
    }

    public String getOscarMelhorAtor() {
        String ator = oscar_atorTextField.getText();
        if (ator.isEmpty()) {
            return null;
        } else {
            return ator;
        }
    }

    public void setOscarMelhorAtor(String ator) {
        oscar_atorTextField.setText(ator);
    }

    //obtem e atualiza componente grafico oscar_atrizTextField
    public String getOscarMelhorAtriz() {
        String atriz = oscar_atrizTextField.getText();
        if (atriz.isEmpty()) {
            return null;
        } else {
            return atriz;
        }
    }

    public void setOscarMelhorAtriz(String atriz) {
        oscar_atrizTextField.setText(atriz);
    }

    //limpa as informacoes existenses nos quatro componentes graficos
    public void limparCampos() {
        oscar_filmeCheckBox.setSelected(false);
        oscar_diretorTextField.setText("");
        oscar_atorTextField.setText("");
        oscar_atrizTextField.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oscar_atorLabel = new javax.swing.JLabel();
        oscar_diretorLabel = new javax.swing.JLabel();
        oscar_atrizLabel = new javax.swing.JLabel();
        oscar_atorTextField = new javax.swing.JTextField();
        oscar_diretorTextField = new javax.swing.JTextField();
        oscar_atrizTextField = new javax.swing.JTextField();
        oscar_filmeCheckBox = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(400, 200));

        oscar_atorLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        oscar_atorLabel.setText("Oscar de melhor Ator");

        oscar_diretorLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        oscar_diretorLabel.setText("Oscar de melhor Diretor");

        oscar_atrizLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        oscar_atrizLabel.setText("Oscar de melhor Atriz");

        oscar_atorTextField.setPreferredSize(new java.awt.Dimension(100, 30));

        oscar_diretorTextField.setPreferredSize(new java.awt.Dimension(100, 30));

        oscar_atrizTextField.setPreferredSize(new java.awt.Dimension(100, 30));

        oscar_filmeCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        oscar_filmeCheckBox.setText("Oscar de Melhor Filme");
        oscar_filmeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oscar_filmeCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(oscar_atrizLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(oscar_atrizTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(oscar_atorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(oscar_atorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(oscar_diretorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oscar_filmeCheckBox)
                            .addComponent(oscar_diretorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(oscar_filmeCheckBox)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oscar_diretorLabel)
                    .addComponent(oscar_diretorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oscar_atorLabel)
                    .addComponent(oscar_atorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oscar_atrizLabel)
                    .addComponent(oscar_atrizTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void oscar_filmeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oscar_filmeCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oscar_filmeCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel oscar_atorLabel;
    private javax.swing.JTextField oscar_atorTextField;
    private javax.swing.JLabel oscar_atrizLabel;
    private javax.swing.JTextField oscar_atrizTextField;
    private javax.swing.JLabel oscar_diretorLabel;
    private javax.swing.JTextField oscar_diretorTextField;
    private javax.swing.JCheckBox oscar_filmeCheckBox;
    // End of variables declaration//GEN-END:variables
}
