/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import entidade.FilmeProvedoraStreaming;

/**
 *
 * @author felip
 */
public class PainelFiltrosFilmeProvedoraStreaming extends javax.swing.JPanel {

    /**
     * Creates new form PainelFiltrosFilmeProvedoraStreaming
     */
    public PainelFiltrosFilmeProvedoraStreaming() {
        initComponents();
    }

    public FilmeProvedoraStreaming.Producao getSelectedProducao() {
        FilmeProvedoraStreaming.Producao producao = null;
        if (producao_filmeButtonGroup.getSelection() != null) {
            producao = FilmeProvedoraStreaming.Producao.values()[producao_filmeButtonGroup.getSelection().getMnemonic()];
        }
        return producao;
    }

    public void limparFiltros() {
        producao_filmeButtonGroup.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        producao_filmeButtonGroup = new javax.swing.ButtonGroup();
        produção_filmeLabel = new javax.swing.JLabel();
        filmeRadioButton = new javax.swing.JRadioButton();
        serieRadioButton = new javax.swing.JRadioButton();

        setLayout(new java.awt.GridBagLayout());

        produção_filmeLabel.setText("Produção Filme");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        add(produção_filmeLabel, gridBagConstraints);

        producao_filmeButtonGroup.add(filmeRadioButton);
        filmeRadioButton.setMnemonic('\u0001');
        filmeRadioButton.setText("filme");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 24, 0, 0);
        add(filmeRadioButton, gridBagConstraints);

        producao_filmeButtonGroup.add(serieRadioButton);
        serieRadioButton.setText("serie");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 26, 0, 0);
        add(serieRadioButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton filmeRadioButton;
    private javax.swing.ButtonGroup producao_filmeButtonGroup;
    private javax.swing.JLabel produção_filmeLabel;
    private javax.swing.JRadioButton serieRadioButton;
    // End of variables declaration//GEN-END:variables
}
