/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import controle.ControladorCadastroClientes;
import controle.ControladorCadastroMotores;
import javax.swing.JOptionPane;
import persistência.BD;

/**
 *
 * @author Gahen
 */
public class JanelaOficinaMecanica extends javax.swing.JFrame {

    /**
     * Creates new form JanelaMotores
     */
    public JanelaOficinaMecanica() {
        BD.criarConexao();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oficina_mecanicaMenuBar = new javax.swing.JMenuBar();
        motorMenu = new javax.swing.JMenu();
        cadastrar_motorMenuItem = new javax.swing.JMenuItem();
        pesquisar_motorMenuItem = new javax.swing.JMenuItem();
        clienteMenu = new javax.swing.JMenu();
        cadastrar_clienteMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Oficina Mecanica");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                terminarSistema(evt);
            }
        });

        motorMenu.setText("Motor");

        cadastrar_motorMenuItem.setText("Cadastrar");
        cadastrar_motorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_motorMenuItemActionPerformed(evt);
            }
        });
        motorMenu.add(cadastrar_motorMenuItem);

        pesquisar_motorMenuItem.setText("Pesquisar");
        pesquisar_motorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarMotor(evt);
            }
        });
        motorMenu.add(pesquisar_motorMenuItem);

        oficina_mecanicaMenuBar.add(motorMenu);

        clienteMenu.setText("Cliente");

        cadastrar_clienteMenuItem.setText("Cadastrar");
        cadastrar_clienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_cliente(evt);
            }
        });
        clienteMenu.add(cadastrar_clienteMenuItem);

        oficina_mecanicaMenuBar.add(clienteMenu);

        setJMenuBar(oficina_mecanicaMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar_motorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_motorMenuItemActionPerformed
        new ControladorCadastroMotores();
    }//GEN-LAST:event_cadastrar_motorMenuItemActionPerformed

    private void terminarSistema(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_terminarSistema
        BD.fechaConexao();
        System.exit(0);
    }//GEN-LAST:event_terminarSistema

    private void pesquisarMotor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarMotor
        informarServicoIndisponivel();
    }//GEN-LAST:event_pesquisarMotor

    private void cadastrar_cliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_cliente
        new ControladorCadastroClientes();
    }//GEN-LAST:event_cadastrar_cliente
    private void informarServicoIndisponivel(){
        JOptionPane.showMessageDialog(this, "Serviço Indisponivel", "Informação",
        JOptionPane.INFORMATION_MESSAGE);
    
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaOficinaMecanica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaOficinaMecanica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaOficinaMecanica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaOficinaMecanica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaOficinaMecanica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrar_clienteMenuItem;
    private javax.swing.JMenuItem cadastrar_motorMenuItem;
    private javax.swing.JMenu clienteMenu;
    private javax.swing.JMenu motorMenu;
    private javax.swing.JMenuBar oficina_mecanicaMenuBar;
    private javax.swing.JMenuItem pesquisar_motorMenuItem;
    // End of variables declaration//GEN-END:variables
}
