/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import controle.ControladorCadastroClientes;
import controle.ControladorCadastroOrdemServicos;
import controle.ControladorCadastroServicos;
import javax.swing.JOptionPane;
import persistência.BD;

/**
 *
 * @author Gahen
 */
public class JanelaOficinaMecanica extends javax.swing.JFrame {

    /**
     * Creates new form JanelaMotores
     */
    public JanelaOficinaMecanica() {
        BD.criarConexao();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oficina_mecanicaMenuBar = new javax.swing.JMenuBar();
        servicoMenu = new javax.swing.JMenu();
        cadastrar_servicoMenuItem = new javax.swing.JMenuItem();
        pesquisar_servicoMenuItem = new javax.swing.JMenuItem();
        clienteMenu = new javax.swing.JMenu();
        cadastrar_clienteMenuItem = new javax.swing.JMenuItem();
        ordemservicoMenu = new javax.swing.JMenu();
        cadastrar_ordemServicoItemMenu = new javax.swing.JMenuItem();
        pesquisar_ordemServicoItemMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Oficina Mecanica");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                terminarSistema(evt);
            }
        });

        servicoMenu.setText("Servico");

        cadastrar_servicoMenuItem.setText("Cadastrar");
        cadastrar_servicoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_servicoMenuItemActionPerformed(evt);
            }
        });
        servicoMenu.add(cadastrar_servicoMenuItem);

        pesquisar_servicoMenuItem.setText("Pesquisar");
        pesquisar_servicoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarMotor(evt);
            }
        });
        servicoMenu.add(pesquisar_servicoMenuItem);

        oficina_mecanicaMenuBar.add(servicoMenu);

        clienteMenu.setText("Cliente");

        cadastrar_clienteMenuItem.setText("Cadastrar");
        cadastrar_clienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_cliente(evt);
            }
        });
        clienteMenu.add(cadastrar_clienteMenuItem);

        oficina_mecanicaMenuBar.add(clienteMenu);

        ordemservicoMenu.setText("Ordem de Servico");

        cadastrar_ordemServicoItemMenu.setText("Cadastrar");
        cadastrar_ordemServicoItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_ordemServicoItemMenuActionPerformed(evt);
            }
        });
        ordemservicoMenu.add(cadastrar_ordemServicoItemMenu);

        pesquisar_ordemServicoItemMenu.setText("Pesquisar");
        pesquisar_ordemServicoItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisar_ordemServicoItemMenuActionPerformed(evt);
                pesquisar_ordemServicoItemMenupesquisarAvaliacoes(evt);
            }
        });
        ordemservicoMenu.add(pesquisar_ordemServicoItemMenu);

        oficina_mecanicaMenuBar.add(ordemservicoMenu);

        setJMenuBar(oficina_mecanicaMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar_servicoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_servicoMenuItemActionPerformed
        new ControladorCadastroServicos();
    }//GEN-LAST:event_cadastrar_servicoMenuItemActionPerformed

    private void terminarSistema(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_terminarSistema
        BD.fechaConexao();
        System.exit(0);
    }//GEN-LAST:event_terminarSistema

    private void pesquisarMotor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarMotor
        informarServicoIndisponivel();
    }//GEN-LAST:event_pesquisarMotor

    private void cadastrar_cliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_cliente
        new ControladorCadastroClientes();
    }//GEN-LAST:event_cadastrar_cliente

    private void cadastrar_ordemServicoItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_ordemServicoItemMenuActionPerformed
        new ControladorCadastroOrdemServicos();

    }//GEN-LAST:event_cadastrar_ordemServicoItemMenuActionPerformed

    private void pesquisar_ordemServicoItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisar_ordemServicoItemMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisar_ordemServicoItemMenuActionPerformed

    private void pesquisar_ordemServicoItemMenupesquisarAvaliacoes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisar_ordemServicoItemMenupesquisarAvaliacoes
        new JanelaPesquisaOrdemServicos().setVisible(true);
    }//GEN-LAST:event_pesquisar_ordemServicoItemMenupesquisarAvaliacoes
    private void informarServicoIndisponivel(){
        JOptionPane.showMessageDialog(this, "Serviço Indisponivel", "Informação",
        JOptionPane.INFORMATION_MESSAGE);
    
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaOficinaMecanica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaOficinaMecanica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaOficinaMecanica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaOficinaMecanica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaOficinaMecanica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrar_clienteMenuItem;
    private javax.swing.JMenuItem cadastrar_ordemServicoItemMenu;
    private javax.swing.JMenuItem cadastrar_servicoMenuItem;
    private javax.swing.JMenu clienteMenu;
    private javax.swing.JMenuBar oficina_mecanicaMenuBar;
    private javax.swing.JMenu ordemservicoMenu;
    private javax.swing.JMenuItem pesquisar_ordemServicoItemMenu;
    private javax.swing.JMenuItem pesquisar_servicoMenuItem;
    private javax.swing.JMenu servicoMenu;
    // End of variables declaration//GEN-END:variables
}
